const reviews = [
    {
        id: 1,
        name: "Aayush",
        emailId : "mt2302101001@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101001.jpg",
        text : "He is currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 2,
        name: "Adit",
        emailId : "mt2302101002@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101002.jpg",
        text : "He is currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 3,
        name: "Aditi",
        emailId : "mt2302101003@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101003.jpg",
        text : "She is currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 4,
        name: "Aditiya",
        emailId : "mt2302101004@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101004.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 5,
        name: "Amardeep",
        emailId : "mt2302101005@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101005.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 6,
        name: "Anukarsh",
        emailId : "mt2302101006@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101006.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 7,
        name: "Anukriti",
        emailId : "mt2302101007@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101007.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 8,
        name: "Apoorav",
        emailId : "mt2302101008@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101008.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 9,
        name: "Dhananjay",
        emailId : "mt2302101009@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101009.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 10,
        name: "Naved",
        emailId : "mt2302101010@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101010.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 11,
        name: "Nitish",
        emailId : "mt2302101011@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101011.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 12,
        name: "Deepak",
        emailId : "mt2302101012@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101012.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 13,
        name: "Shabbier",
        emailId : "mt2302101013@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101013.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 14,
        name: "Vikas Chauhan",
        emailId : "mt2302101014@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101014.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 15,
        name: "Sonu",
        emailId : "mt2302101016@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101016.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    },
    {
        id: 16,
        name: "Uzzal",
        emailId : "mt2302101017@iiti.ac.in",
        image : "https://cse.iiti.ac.in/stu_pics/mtech/2302101017.jpg",
        text : "He xis currently pursuing an M.Tech at IIT Indore, having successfully cleared the GATE exam, which showcases their strong academic foundation and dedication to their field. Their journey at one of India's premier institutions is driven by a passion for research and innovation. With a focus on [specialization/area of study], they are actively engaging in projects and coursework that aim to push the boundaries of current technological understanding. [Name] is committed to applying their knowledge to solve real-world problems and contribute to advancements in their chosen field.",
    }
]

export default reviews;